// Generated by CoffeeScript 1.7.1
(function() {
  var PLUGIN_NAME, PluginError, fs, getFilenames, gutil, path, stripFilename, through;

  path = require("path");

  gutil = require("gulp-util");

  PluginError = gutil.PluginError;

  through = require("through2");

  fs = require("fs");

  PLUGIN_NAME = "gulp-getFilenames";

  stripFilename = function(p) {
    var extname;
    extname = path.extname(p);
    return path.basename(p, extname);
  };

  getFilenames = function(options) {
    var Json, exists, newData, stream;
    if (options == null) {
      options = {
        fileName: "./data/my-imagedata.json"
      };
    }
    Json = path.join(process.cwd(), options.fileName);
    exists = fs.existsSync(Json);
    if (!exists) {
      newData = [];
      fs.writeFileSync(Json, JSON.stringify(newData));
    }
    stream = through.obj(function(file, enc, cb) {
      var bn, data, p;
      if (exists) {
        this.push(file);
        return cb();
      } else {
        p = file.path;
        bn = stripFilename(p);
        console.log(bn);
        data = require(Json);
        data.push({
          className: bn,
          hex: ""
        });
        fs.writeFileSync(Json, JSON.stringify(data, null, 2));
        this.push(file);
        return cb();
      }
    });
    return stream;
  };

  module.exports = getFilenames;

}).call(this);

//# sourceMappingURL=index.map
